spring:
  redis:
    dynamic:
      datasource:
        master:
         database: 0
        slave:
          database: 1
          host: 10.197.72.27
          port: 6379
          #    password:
          jedis:
            pool:
              max-active: 50
              max-wait: 10
              max-idle: 10
              min-idle: 0